export enum StringTemplates {
  ADMIN_TITLE = 'PSAdminTitle',
  CONFIG_FOR_TITLE = 'PSAdminConfigForTitle',
  CONFIG_FOR_MYSELF = 'PSAdminConfigForMyself',
  CONFIG_FOR_EVERYONE = 'PSAdminConfigForEveryone',
  ENABLED = 'PSAdminEnabled',
  DISABLED = 'PSAdminDisabled',
  DOCS = 'PSAdminDocs',
  SAVE = 'PSAdminSave',
  CANCEL = 'PSAdminCancel',
  REVERT_WORKER_TO_GLOBAL = 'PSAdminRevertWorkerToGlobal',
  MORE_SETTINGS = 'PSAdminMoreSettings',
  NO_MORE_SETTINGS = 'PSAdminNoMoreSettings',
  FILTER_FEATURES = 'PSAdminFilterFeatures',
  MODAL_SETTINGS_TITLE = 'PSAdminModalSettingsTitle',
  SAVE_ERROR = 'PSAdminSaveError',
  SAVE_SUCCESS = 'PSAdminSaveSuccess',
}

export const stringHook = () => ({
  [StringTemplates.ADMIN_TITLE]: 'Feature Settings',
  [StringTemplates.CONFIG_FOR_TITLE]: 'Configure for:',
  [StringTemplates.CONFIG_FOR_MYSELF]: 'Myself',
  [StringTemplates.CONFIG_FOR_EVERYONE]: 'Everyone',
  [StringTemplates.ENABLED]: 'Enabled',
  [StringTemplates.DISABLED]: 'Disabled',
  [StringTemplates.DOCS]: 'Docs',
  [StringTemplates.SAVE]: 'Save',
  [StringTemplates.CANCEL]: 'Cancel',
  [StringTemplates.REVERT_WORKER_TO_GLOBAL]: 'Revert to global setting',
  [StringTemplates.MORE_SETTINGS]: 'More settings',
  [StringTemplates.NO_MORE_SETTINGS]: 'This feature has no additional settings',
  [StringTemplates.FILTER_FEATURES]: 'Filter features...',
  [StringTemplates.MODAL_SETTINGS_TITLE]: '{{feature}} settings',
  [StringTemplates.SAVE_ERROR]: 'There was an error saving the changes. Please try again.',
  [StringTemplates.SAVE_SUCCESS]: 'Changes saved successfully. Reload Flex for changes to take effect.',
});
