export enum FlexEvent {
  chatChannelJoining = 'chatChannelJoining',
  connectionStateChanged = 'connectionStateChanged',
  flexError = 'flexError',
  flexSplitterResize = 'flexSplitterResize',
  notesSubmitted = 'notesSubmitted',
  pluginsInitialized = 'pluginsInitialized',
  selectedViewChanged = 'selectedViewChanged',
  sessionInvalidated = 'sessionInvalidated',
  sessionValidated = 'sessionValidated',
  taskAccepted = 'taskAccepted',
  taskCanceled = 'taskCanceled',
  taskCompleted = 'taskCompleted',
  taskReceived = 'taskReceived',
  taskRejected = 'taskRejected',
  taskRescinded = 'taskRescinded',
  taskTimeout = 'taskTimeout',
  taskUpdated = 'taskUpdated',
  taskWrapup = 'taskWrapup',
  tokenExpired = 'tokenExpired',
  tokenUpdated = 'tokenUpdated',
  viewResized = 'viewResized',
  workerActivityUpdated = 'workerActivityUpdated',
  workerAttributesUpdated = 'workerAttributesUpdated',
}
