// Export the template names as an enum for better maintainability when accessing them elsewhere
export enum StringTemplates {
  TeamsViewColumnTeamName = 'PSTeamsViewColumnTeamName',
  TeamsViewColumnDepartment = 'PSTeamsViewColumnDepartment',
  TeamsViewColumnLocation = 'PSTeamsViewColumnLocation',
  TeamsViewColumnSkills = 'PSTeamsViewColumnSkills',
  TeamsViewSummaryAllTeams = 'PSTaskSummaryAllTeams',
  TeamsViewSummaryOther = 'PSTeamsViewSummaryOther',
  TeamsViewSummaryTotalTasks = 'PSTeamsViewSummaryTotalTasks',
  TeamsViewSummaryInbound = 'PSTeamsViewSummaryInbound',
  TeamsViewSummaryOutbound = 'PSTeamsViewSummaryOutbound',
  TeamsViewSummaryTotalAgents = 'PSTeamsViewSummaryTotalAgents',
  ChannelCapacityTitle = 'PSChannelCapacityTitle',
  ChannelCapacityTasks = 'PSChannelCapacityTasks',
  ChannelCapacityUsed = 'PSChannelCapacityUsed',
  ChannelCapacityMax = 'PSChannelCapacityMax',
  StatusIdleLabel = 'PSStatusIdleLabel',
  StatusIdleTooltip = 'PSStatusIdleTooltip',
  StatusBusyLabel = 'PSStatusBusyLabel',
  StatusBusyTooltip = 'PSStatusBusyTooltip',
}

export const stringHook = () => ({
  'en-US': {
    [StringTemplates.TeamsViewColumnTeamName]: 'Team Name',
    [StringTemplates.TeamsViewColumnDepartment]: 'Department',
    [StringTemplates.TeamsViewColumnLocation]: 'Location',
    [StringTemplates.TeamsViewColumnSkills]: 'Skills',
    [StringTemplates.TeamsViewSummaryAllTeams]: 'All Teams',
    [StringTemplates.TeamsViewSummaryOther]: 'Other',
    [StringTemplates.TeamsViewSummaryTotalTasks]: 'Total Tasks',
    [StringTemplates.TeamsViewSummaryInbound]: 'Inbound Calls',
    [StringTemplates.TeamsViewSummaryOutbound]: 'Outbound Calls',
    [StringTemplates.TeamsViewSummaryTotalAgents]: 'Total Agents',
    [StringTemplates.StatusIdleLabel]: 'Idle',
    [StringTemplates.StatusIdleTooltip]: 'Idle: Available with no Tasks',
    [StringTemplates.StatusBusyLabel]: 'Busy',
    [StringTemplates.StatusBusyTooltip]: 'Busy: Available with Task(s)',
  },
  'es-MX': {
    [StringTemplates.TeamsViewColumnTeamName]: 'Equipo',
    [StringTemplates.TeamsViewColumnDepartment]: 'Departamento',
    [StringTemplates.TeamsViewColumnLocation]: 'Lugar',
    [StringTemplates.TeamsViewColumnSkills]: 'Habilidades',
    [StringTemplates.TeamsViewSummaryAllTeams]: 'Todos Equipos',
    [StringTemplates.TeamsViewSummaryOther]: 'Otros',
    [StringTemplates.TeamsViewSummaryTotalTasks]: 'Todas Tareas',
    [StringTemplates.TeamsViewSummaryInbound]: 'Llamadas entrantes',
    [StringTemplates.TeamsViewSummaryOutbound]: 'Llamadas salientes',
    [StringTemplates.TeamsViewSummaryTotalAgents]: 'Agentes totales',
    [StringTemplates.StatusIdleLabel]: 'Inactiva',
    [StringTemplates.StatusIdleTooltip]: 'Inactiva: Disponible sin tareas',
    [StringTemplates.StatusBusyLabel]: 'Ocupada',
    [StringTemplates.StatusBusyTooltip]: 'Ocupada: Disponible con tarea(s)',
  },
});
