import esES from './es-es.json';
import esMX from './es-mx.json';
import ptBR from './pt-br.json';
import th from './th.json';
import zhHans from './zh-hans.json';

export enum StringTemplates {
  TITLE = 'MassWorkerUpdateTitle',
  SIDE_LINK = 'MassWorkerUpdateSideLink',
  SECTION_IDENTIFY = 'MassWorkerUpdateSectionIdentify',
  SECTION_IDENTIFY_TEXT = 'MassWorkerUpdateSectionIdentifyText',
  SECTION_MUTATE = 'MassWorkerUpdateSectionMutate',
  SECTION_MUTATE_TEXT = 'MassWorkerUpdateSectionMutateText',
  FILTER_TEAM = 'MassWorkerUpdateFilterTeam',
  FILTER_DEPARTMENT = 'MassWorkerUpdateFilterDepartment',
  FILTER_SKILL = 'MassWorkerUpdateFilterSkill',
  NONE = 'MassWorkerUpdateFilterNone',
  IDENTIFY_BUTTON = 'MassWorkerUpdateIdentifyButton',
  IDENTIFY_MATCH_COUNT = 'MassWorkerUpdateIdentifyMatchCount',
  IDENTIFY_EMPTY = 'MassWorkerUpdateIdentifyEmpty',
  IDENTIFY_LIMIT_WARNING = 'MassWorkerUpdateIdentifyLimitWarning',
  SKILLS_TO_ADD = 'MassWorkerUpdateSkillsToAdd',
  SKILLS_TO_REMOVE = 'MassWorkerUpdateSkillsToRemove',
  CONFIRM_BUTTON = 'MassWorkerUpdateConfirmButton',
  CONFIRM_DIALOG_TITLE = 'MassWorkerUpdateConfirmDialogTitle',
  CONFIRM_DIALOG_TEXT = 'MassWorkerUpdateConfirmDialogText',
  CONFIRM_YES = 'MassWorkerUpdateConfirmYes',
  CONFIRM_NO = 'MassWorkerUpdateConfirmNo',
  PROGRESS_TITLE = 'MassWorkerUpdateProgressTitle',
  PROGRESS_TEXT = 'MassWorkerUpdateProgressText',
  PROGRESS_STARTED_BY = 'MassWorkerUpdateProgressStartedBy',
  CANCEL_BUTTON = 'MassWorkerUpdateCancelButton',
  CANCELLED = 'MassWorkerUpdateCancelled',
  STALE_TITLE = 'MassWorkerUpdateStaleTitle',
  STALE_TEXT = 'MassWorkerUpdateStaleText',
  RESET_BUTTON = 'MassWorkerUpdateResetButton',
  COLUMN_NAME = 'MassWorkerUpdateColumnName',
  COLUMN_SID = 'MassWorkerUpdateColumnSid',
  COLUMN_TEAM = 'MassWorkerUpdateColumnTeam',
  COLUMN_DEPARTMENT = 'MassWorkerUpdateColumnDepartment',
  COLUMN_SKILLS = 'MassWorkerUpdateColumnSkills',
  ERROR_NO_FILTER = 'MassWorkerUpdateErrorNoFilter',
  ERROR_NO_SKILL_MUTATION = 'MassWorkerUpdateErrorNoSkillMutation',
  ERROR_TOO_MANY_WORKERS = 'MassWorkerUpdateErrorTooManyWorkers',
  ERROR_IDENTIFY = 'MassWorkerUpdateErrorIdentify',
  ERROR_EXECUTE = 'MassWorkerUpdateErrorExecute',
  ERROR_RESET = 'MassWorkerUpdateErrorReset',
  SUCCESS_UPDATED = 'MassWorkerUpdateSuccessUpdated',
}

export const stringHook = () => ({
  'en-US': {
    [StringTemplates.TITLE]: 'Mass Worker Update',
    [StringTemplates.SIDE_LINK]: 'Mass Worker Update',
    [StringTemplates.SECTION_IDENTIFY]: '1. Identify workers',
    [StringTemplates.SECTION_IDENTIFY_TEXT]:
      'Pick at most one team, department, and skill. Workers must match ALL selected filters.',
    [StringTemplates.SECTION_MUTATE]: '2. Choose skills to add and remove',
    [StringTemplates.SECTION_MUTATE_TEXT]: 'Skills not mentioned in either list will stay untouched on each worker.',
    [StringTemplates.FILTER_TEAM]: 'Team',
    [StringTemplates.FILTER_DEPARTMENT]: 'Department',
    [StringTemplates.FILTER_SKILL]: 'Skill',
    [StringTemplates.NONE]: 'Any',
    [StringTemplates.IDENTIFY_BUTTON]: 'Identify workers',
    [StringTemplates.IDENTIFY_MATCH_COUNT]: '{{count}} matching worker(s)',
    [StringTemplates.IDENTIFY_EMPTY]: 'No workers match the current filters. Adjust the filters and try again.',
    [StringTemplates.IDENTIFY_LIMIT_WARNING]:
      'Match count ({{count}}) exceeds the configured maximum ({{limit}}). Narrow the filter before running the update.',
    [StringTemplates.SKILLS_TO_ADD]: 'Skills to add',
    [StringTemplates.SKILLS_TO_REMOVE]: 'Skills to remove',
    [StringTemplates.CONFIRM_BUTTON]: 'Confirm update',
    [StringTemplates.CONFIRM_DIALOG_TITLE]: 'Update {{count}} workers?',
    [StringTemplates.CONFIRM_DIALOG_TEXT]:
      'The selected workers will have skills added and/or removed. This cannot be undone automatically.',
    [StringTemplates.CONFIRM_YES]: 'Confirm',
    [StringTemplates.CONFIRM_NO]: 'Cancel',
    [StringTemplates.PROGRESS_TITLE]: 'Mass worker update in progress',
    [StringTemplates.PROGRESS_TEXT]: 'Updated {{processed}} of {{total}} workers…',
    [StringTemplates.PROGRESS_STARTED_BY]: 'Started by {{startedBy}}',
    [StringTemplates.CANCEL_BUTTON]: 'Cancel',
    [StringTemplates.CANCELLED]: 'The mass worker update was cancelled.',
    [StringTemplates.STALE_TITLE]: 'Operation appears stuck',
    [StringTemplates.STALE_TEXT]:
      'The mass worker update has not reported progress recently. This can happen when the server function times out. Reset the shared state to unlock this screen.',
    [StringTemplates.RESET_BUTTON]: 'Reset state',
    [StringTemplates.COLUMN_NAME]: 'Name',
    [StringTemplates.COLUMN_SID]: 'Worker SID',
    [StringTemplates.COLUMN_TEAM]: 'Team',
    [StringTemplates.COLUMN_DEPARTMENT]: 'Department',
    [StringTemplates.COLUMN_SKILLS]: 'Current skills',
    [StringTemplates.ERROR_NO_FILTER]: 'Select at least one filter (team, department, or skill).',
    [StringTemplates.ERROR_NO_SKILL_MUTATION]: 'Add or remove at least one skill before confirming.',
    [StringTemplates.ERROR_TOO_MANY_WORKERS]: 'Too many workers match. Narrow the filter to {{limit}} or fewer.',
    [StringTemplates.ERROR_IDENTIFY]: 'Failed to identify workers. See browser console for details.',
    [StringTemplates.ERROR_EXECUTE]: 'Mass worker update failed. See browser console for details.',
    [StringTemplates.ERROR_RESET]: 'Failed to reset the shared state.',
    [StringTemplates.SUCCESS_UPDATED]: 'Updated {{processed}} workers.',
  },
  'es-MX': esMX,
  'pt-BR': ptBR,
  th,
  'zh-Hans': zhHans,
  'es-ES': esES,
});
