name: Docs checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - 'docs/**'
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: ${{ vars.DEPLOY_DOCS == 'true' }}
    runs-on: ubuntu-latest-large
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: setup node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: '20'
      - name: Install packages
        working-directory: ./docs
        run: npm install
      - name: Run build
        working-directory: ./docs
        run: npm run build
